server.port: 8080
spring.application.name: store-api

api.products.endpoint.url: http://localhost:8080/products

# expondo rotas: /actuator/<health, info, metrics, prometheus>
management:
  endpoints.web.exposure.include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      slo[http.server.requests]: "25ms, 50ms, 100ms, 200ms, 400ms, 800ms, 1500ms"
  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: true
          base-url: http://localhost:9091
          shutdown-operation: POST
          push-rate: PT1S
          job: store-api-push
